Docu review and minor changes
chain4travel/camino-messenger-protocol pull request #25
Opened 2024-08-22 15:17 UTC by SamJaarsma

Added or updated:
- General explanation on Activity Product, Unit and Service structure.
- Updated PriceTypes and better explained their purpose when used in price breakdowns
- Updated and better explained Locations and TransferZones, PickUp and DropOff

2024-08-23 16:27 UTC, mo-c4t commented
I think you need to update your branch to get the latest changes from c4t branch, because it has some commits that were already merged to c4t

2024-08-23 16:29 UTC, mo-c4t commented on proto/cmp/types/v1alpha/price_type.proto
>    oneof type {
what's the use of oneof here if it's one option ?

2024-08-23 16:31 UTC, mo-c4t commented on proto/cmp/services/activity/v1alpha/activity_types.proto
> +  // Activity static info
does activity has dynamic or static info ?!

2024-08-23 19:08 UTC, havan requested changes
I've left some comments to be addressed. 

There are also some small typos like uppercase/lowercase etc, but I will just update them and push to this branch.

2024-08-23 19:08 UTC, havan commented on proto/cmp/services/activity/v1alpha/activity_types.proto
> +  // Activity static info
Yes, the "dynamic" was correct. `Activity` type is used in the search results. The `ActivityExtendedInfo` is the "static" info.

2024-08-23 19:08 UTC, havan commented on proto/cmp/types/v1alpha/price_type.proto
> -    FeeCode fee_code = 4;
Why did we removed those? If you removed them because you've added tax and fee items into the `PriceType` enum, that will not work. Because now the `TaxCode` and `FeeCode` enums don't have any fields defined for them.

In this current state, one can not select any enum from `TaxCode` or `FeeCode`.

I suggest we do it like:
```js
  oneof type {
    PriceType price = 2;
    TaxCode tax = 3;
    FeeCode fee = 4;
  }
```

2024-08-26 07:51 UTC, SamJaarsma commented on proto/cmp/services/activity/v1alpha/activity_types.proto
> +  // Activity static info
Yes, correct. Explained this section a bit better

2024-08-26 07:58 UTC, mo-c4t approved these changes

2024-08-26 13:29 UTC, havan approved these changes

2024-08-26 13:31 UTC, merged