Transport list
chain4travel/camino-messenger-protocol pull request #47
Opened 2024-10-09 08:47 UTC by mo-c4t

* Add transport list service
* Add schedule for the whole trip in Trip message

2024-10-11 11:53 UTC, SamJaarsma approved these changes
LGTM

2024-10-16 11:06 UTC, havan reviewed
I have some comments about the new Trip types and some minor typos.

2024-10-16 11:06 UTC, havan commented on proto/cmp/services/transport/v3/search.proto
> +// dynamic data. Static data can be cached and kept up to data with the Product List
```suggestion
// dynamic data. Static data can be cached and kept up to date with the Product List
```
Typo

2024-10-16 11:06 UTC, havan commented on proto/cmp/services/transport/v3/trip_types.proto
> +  cmp.types.v2.Price price = 3;
Previously we had the `price` in the `TripSegment`. Which means it was possible to define prices for individual segments. And now it's not. Is that intentional?

2024-10-16 11:06 UTC, havan commented on proto/cmp/services/transport/v3/trip_types.proto
> +  repeated cmp.services.transport.v3.SegmentInfo segments = 4;
We have the segments in the `Trip` type and also here. Why is that? Isn't that means we have the same info in two different places in the same service?

2024-10-16 11:06 UTC, havan commented on proto/cmp/services/transport/v3/trip_types.proto
> +  // or a price detail can be included for optionally pre-ordered meals for example.
```suggestion
  // Included, optional or compulsory services for this segment or leg. Just a code and
  // description can be included if it is a package (seat, priority, large carry-on).
  // or a price detail can be included for optionally pre-ordered meals for example.
```
Typo

2024-10-16 11:06 UTC, havan commented on proto/cmp/services/transport/v3/trip_types.proto
> +  // DB could be selling an intenational train trip operated by the Dutch Nederlands
```suggestion
  // DB could be selling an international train trip operated by the Dutch Nederlands
```
Typo

2024-10-16 11:35 UTC, havan commented on proto/cmp/services/transport/v3/trip_types.proto
> +  repeated cmp.services.transport.v3.SegmentInfo segments = 4;
Oh, this is `SegmentInfo` type, not `TripSegment`. This is confusing, why we have segment info in the trip schedule type?

2024-10-17 12:53 UTC, havan requested changes
There are a typo and wrong versions diagram links.

2024-10-17 12:53 UTC, havan commented on proto/cmp/services/transport/v3/search.proto
> +  repeated cmp.types.v1.ContentSourceType conten_source_types = 3;
```suggestion
  // Content source types for this search request.
  //
  // Ex: ContentSourceType.CONTENT_SOURCE_TYPE_GDS,
  // ContentSourceType.CONTENT_SOURCE_TYPE_NDC
  // ContentSourceType.CONTENT_SOURCE_TYPE_3RD_PARTY
  repeated cmp.types.v1.ContentSourceType content_source_types = 3;
```
Typo

2024-10-17 12:53 UTC, havan commented on proto/cmp/services/transport/v3/search_result_types.proto
> +message TransportSearchResult {
```suggestion
// Transport search result
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search_result_types.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search_result_types.proto.dot.svg)
message TransportSearchResult {
```
Wrong version in diagram URL.

2024-10-17 12:53 UTC, havan commented on proto/cmp/services/transport/v3/search.proto
> +service TransportSearchService {
```suggestion
// Takes `TransportSearchRequest` message type and returns `TransportSearchResponse`
// message type.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search.proto.dot.svg)
service TransportSearchService {
```
Wrong version in diagram URLs.

2024-10-17 22:09 UTC, havan approved these changes

2024-10-17 22:11 UTC, merged